name: PROFILE-3D

on:
  schedule: # 스케줄
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-profile
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: generate-3d-contrib
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: commit-push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "github 3d profile updated"; then
            git push
          fi