name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # 2시간마다 업데이트
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: README.md 업데이트
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""