name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # 6시간마다 업데이트
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    name: README.md 업데이트
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}